### ISSUE TITLE
Buttons are not working

### ISSUE THREAD

**Issue by tufail** [artcoded-net/vendure-plugins#1]
Hi @artcoded-net 
I need your help to install this plugin, I configured this Extended Shipping Plugin but are facing few issues like buttons are disabled while creating a shipping method.   Please help me with complete document how can I configure this.
![image](https://user-images.githubusercontent.com/377556/171087032-f712ccfe-3f23-4c6b-a326-998bf47e9988.png)

**Comment by tufail** [comment]
Sorry it is working now..

**Comment by coderjib** [comment]
Ok great!
